version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        volumes:
            - ./public:/app/public
            # Add any other volumes you need for data persistence

    # Add other services like database, cache, etc. if needed
